
version: 2
jobs:
    lint_js:
        docker:
            - image: circleci/node:10.16

        working_directory: ~/repo
  
        steps:
            - checkout

            # Download and cache dependencies
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    # fallback to using the latest cache if no exact match is found
                    - v1-dependencies-

            - run: yarn install

            - save_cache:
                paths:
                    - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}

            # run tests!
            - run: yarn lint

    test_js:
        docker:
            - image: circleci/node:10.16

        working_directory: ~/repo
  
        steps:
            - checkout

            # Download and cache dependencies
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    # fallback to using the latest cache if no exact match is found
                    - v1-dependencies-

            - run: yarn install

            - save_cache:
                paths:
                    - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}

            # run tests!
            - run: yarn test

workflows:
    version: 2
        lint_and_test:
            jobs:
                - lint_js
                - test_js
